name: create-s3-bucket
run-name: Manual pipeline to create s3 bucket for storing terraform state
on:
  - workflow_dispatch

jobs:
  creates3bucket:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create ${{ vars.BUCKET_NAME }} S3 bucket if it does not exist
        run: |
          BUCKET_EXISTS=$(aws s3api head-bucket --bucket ${{ vars.BUCKET_NAME }} 2>&1 || true)
          if [ -z "$BUCKET_EXISTS" ]; then
            echo "Bucket already exists, will not create."
          else
            aws s3api create-bucket --acl private --bucket ${{ vars.BUCKET_NAME }} --create-bucket-configuration LocationConstraint=${{ vars.AWS_DEFAULT_REGION }}
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
