# https://github.com/marketplace/actions/build-and-push-docker-images
name: build-and-push-docker-images
run-name: Build and publish 
on:
  push:
    branches:
      - 'main'

env:
  IMAGE_PREFIX: 'xalt'
  IMAGE_NAME: 'bamboo-hanging-builds-notifier'
  IMAGE_TAG: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
